import React, { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Slider from "@mui/material/Slider";
import Box from "@mui/material/Box";
import findDescriptions, { marks } from "./data/slider_data";
import NavigateNextIcon from "@mui/icons-material/NavigateNext";
import Breadcrumbs from "@mui/material/Breadcrumbs";
import BackgroundInfo from "./components/BackgroundInfo";
const About: NextPage = () => {
  const [value, setValue] = React.useState<number | number[]>(100);

  const breadcrumbs = [
    <Link href="/" key="1">
      Home
    </Link>,
    <Link href="/about" key="2">
      About
    </Link>,
    <Link href="/now" key="3">
      Now
    </Link>,
  ];

  return (
    <div className={styles.main}>
      <Head>
        <title>About | Nam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <Breadcrumbs
          separator={<NavigateNextIcon fontSize="small" />}
          aria-label="breadcrumb"
        >
          {breadcrumbs}
        </Breadcrumbs>
        <h1 className={styles.title}>About Nam</h1>
        <Box
          sx={{
            height: 150,
          }}
        >
          {" "}
          <p className={styles.description}>{findDescriptions(value)}</p>
        </Box>

        <Box width={"100%"}>
          <Slider
            aria-label="Restricted values"
            defaultValue={100}
            step={null}
            valueLabelDisplay="off"
            marks={marks}
            onChange={(_, value) => setValue(value)}
            onChangeCommitted={(_, value) => setValue(value)}
            sx={{ color: "#eee" }}
          />
        </Box>
      </div>

      <div className={styles.main}>
        <h1 className={styles.title}>Education and Career</h1>
        <BackgroundInfo></BackgroundInfo>
      </div>

      <div className={styles.main}>
        <h1 className={styles.title}>Projects</h1>
        <h2 className={styles.subtitle} style={{ marginTop: "2rem" }}>
          The Music Confabulation
        </h2>
        <p className={styles.description}>
          A music blog to share your stories and memories or simply to introduce
          others about your favorite artists. Built using Bootstrap, JavaScript,
          NodeJS (Express), MongoDB, and Heroku.
        </p>
        <hr style={{ width: "100%" }}></hr>
        <h2 className={styles.subtitle}>
          The Music Confabulation - Visualization
        </h2>
        <p className={styles.description}>
          A music blog to share your stories and memories or simply to introduce
          others about your favorite artists. Built using Bootstrap, JavaScript,
          NodeJS (Express), MongoDB, and Heroku.
        </p>
        <hr style={{ width: "100%" }}></hr>
        <h2 className={styles.subtitle}>
          Examining the Usage of the UMBC High Performance Computing Facility{" "}
        </h2>
        <p className={styles.description}>
          A compelling visualizations that provide insight into the usage
          patterns of the HPCF. This assists the faculty in allocating resources
          towards the facility and determining future policies on this shared
          UMBC community resource. The visualization also help evaluates the
          COVID-19 lockdown impact on the UMBC users usage habits.
        </p>
      </div>

      <footer className={styles.footer}>Copyright © Nam</footer>
    </div>
  );
};

export default About;
