import React, { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import BackgroundInfo from "../components/BackgroundInfo/BackgroundInfo";
import ProjectInfo from "../components/ProjectInfo/ProjectInfo";
import Slider from "../components/Slider/Slider";
import Header from "../components/Header/Header";

const About: NextPage = () => {
  return (
    <div className={styles.main}>
      <Head>
        <title>About | Nam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <div className={styles.main}>
        <h1 className={styles.title}>About Nam</h1>
        <Slider></Slider>
      </div>

      <div className={styles.main}>
        <h1 className={styles.title}>Education and Career</h1>
        <BackgroundInfo></BackgroundInfo>
      </div>

      <div className={styles.main}>
        <h1 className={styles.title}>Projects</h1>
        <ProjectInfo></ProjectInfo>
      </div>

      <footer className={styles.footer}>Copyright © Nam</footer>
    </div>
  );
};

export default About;
