import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.page}>
      <Head>
        <title>Home | Nam</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.wrapper}>
          <div className={styles.card}>
            <Link href="/about" passHref>
              <div>
                <h2>About</h2>
              </div>
            </Link>
          </div>

          <div className={styles.card}>
            <Link href="/now" passHref>
              <div>
                <h2>Now</h2>
              </div>
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
